agent_name: ["hybrid-search", "query-agent-search-only"]
agents_host: https://api.agents.weaviate.io
dataset: bright/biology
use_async: True
use_subset: True
num_samples: 5
num_trials: 1
batch_size: 5
max_concurrent: 5
experiment_name: hybrid-search