agent_name: "hybrid-search"
dataset: irpapers/text

use_async: True
max_concurrent: 5

use_subset: False
num_samples: 10

num_trials: 1
batch_size: 5

agents_host: https://api.agents.weaviate.io
embedding_models: 
- "Snowflake/snowflake-arctic-embed-l-v2.0"
- "Snowflake/snowflake-arctic-embed-m-v1.5"